Simplify build pipeline so it works in production mode
The babel config was actually useless and buggy in production mode,
which led to extremely confusing errors like this:

    Error: The default export is not a React Component in page: "/"

Or claims that "Document" is not a React component, while it actually
is one.